<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
        const PENDING = 'pending';
        const RESOLVED = 'resolved';
        const REJECTED = 'rejected';

        function Promise(executor) {
            let self = this; // 缓存this
            self.state = PENDING; // 默认状态为pending
            self.value = undefined; // 存放着此promise的结果
            self.onResolvedCallbacks = []; // 存放着所有成功的回调函数
            self.onRejectedCallbacks = []; // 存放着所有失败的回调函数

            // 调用resolve方法可以把promise状态改成成功态
            function resolve(value) {
                if (value instanceof Promise) {
                    return value.then(resolve, reject);
                }

                setTimeout(function () { // 异步执行所有的回调
                    // 如果当前状态为初始态（pending），则转成成功态
                    // 此处写这个判断的原因是因为resolved和rejected两个状态只能从pending转化而来，两者不能相互转化
                    if (self.state === PENDING) {
                        self.state = RESOLVED;
                        self.value = value;
                        self.onRejectedCallbacks.forEach(cb => cb(value));
                    }
                });
            }

            // 调用reject方法可以把promise状态改成失败态
            function reject(value) {
                setTimeout(function () {
                    if (self.state === PENDING) {
                        self.state = REJECTED;
                        self.value = value;
                        self.onRejectedCallbacks.forEach(cb => cb(value));
                    }
                })
            }
           
            // 立即执行传入的任务
            try {
                executor(resolve, reject);
            } catch(e) {
                reject(e);
            }
        };

        // resolvePromise函数的目的是与原生Promise相兼容，可以互相调用
        function resolvePromise(promise2, x, resolve, reject) {
            // 将返回的promise递归执行，直到失败或者返回一个普通的数据类型
            if (promise2 === x) return reject(new TypeError('循环引用'));

            let then, called;

            if (x != null && ((typeof x === 'object') || isFunction(x))) {
                // promise
                try {
                    then = x.then;
                    if (isFunction(then)) {
                        then.call(x, function(value) {
                            if (called) return;
                            called = true;
                            resolvePromise(promise2, value, resolve, reject);
                        }, function(reason) {
                            if (called) return;
                            called = true;
                            reject(reason);
                        })
                    } else {
                        resolve(x);
                    }
                } catch(e) {
                    if (called) return;
                    called = true;
                    reject(x);
                }
            } else {
                resolve(x);
            }
        }

        // onFulfilled 成功后的回调，onRejected失败后的回调
        Promise.prototype.then = function(onFulfilled, onRejected) {
            let self = this;
            // 当调用没有写函数，给他一个默认函数
            onFulfilled = isFunction(onFulfilled) ? onFulfilled : function (value) {
                return value
            };
            onRejected = isFunction(onRejected) ? onRejected : function (value) {
                throw value;
            };
            let promise2;
            if (self.state === RESOLVED) {
                promise2 = new Promise(function(resolve, reject) {
                    try {
                        let x = onFulfilled(self.value);
                        resolvePromise(promise2, x, resolve, reject);
                    } catch (e) {
                        reject(e);
                    }
                })
            }

            if (self.state === REJECTED) {
                promise2 = new Promise(function(resolve, reject) {
                    try {
                        let x = onRejected;
                        resolvePromise(promise2, x, resolve, reject);
                    } catch (e) {
                        reject(e);
                    }
                })
            }

            if (self.state === PENDING) {
                // 当还处于pending状态时，将回调存入数组中。
                promise2 = new Promise(function(resolve, reject) {
                    self.onRejectedCallbacks.push(function(value) {
                        try {
                            let x = onFulfilled(value);
                            resolvePromise(promise2, x, resolve, reject);
                        } catch (e) {
                            reject(e);
                        }
                    })
                    self.onRejectedCallbacks.push(function(value) {
                        try {
                            let x = onRejected(value);
                            resolvePromise(promise2, x, resolve, reject);
                        } catch (e) {
                            reject(e);
                        }
                    })
                })
            }
            
            return promise2;
        }

        // catch实际上是then的一个简写，成功回调传空即可
        Promise.prototype.catch = function(onRejected) {
            return this.then(null, onRejected);
        }

        // Promise.resolve(value) 是和 Promise.reject(error) 类似的静态方法，是 new Promise() 方法的快捷方式。
        Promise.resolve = function(value) {
            return new Promise(function(resolve, reject) {
                if (value != null && typeof value === 'object' && isFunction(value.then)) {
                    value.then();
                } else {
                    resolve(value);
                }
            })
        }
        
        Promise.reject = function(reason) {
            return new Promise(function(reject, resolve) {
                reject(reason);
            })
        }

        Promise.prototype.all = function(promises) {
            return new Promise(function(resolve, reject) {
                let result = [];
                let count = 0;
                for (let i = 0; i < promises.length; i++) {
                    promises[i].then(function(data) {
                        result[i] = data;
                        if (++count === promises.length) {
                            resolve(result);
                        }
                    }, function(err) {
                        reject(err);
                    })
                }
            })
        }

        // race 方法可以传入多个
        Promise.race = function(promises) {
            return new Promise(function(resolve, reject) {
                for (let i = 0;i < promises.length; i++) {
                    promises[i].then(function(data) {
                        resolve(data);
                    }, function(err) {
                        reject(err);
                    })
                }
            })
        }

        Promise.deferred = Promise.defer = function() {
            const defer = {};
            defer.promise = new Promise(function(resolve, reject) {
                defer.resolve = resolve;
                defer.reject = reject;
            })
            return defer;
        }

        function isFunction(obj) {
            return typeof obj === 'function';
        }

        const p = new Promise(function(resolve, reject) {
            setTimeout(() => {
                console.log(1.1)
                resolve(666);
            }, 1000)
            console.log(111);
        }).then((res) => {
            console.log(res, 222);
            setTimeout(() => {
                console.log(444);
                return 333;
            }, 1000)
        }).then((res) => {
            console.log(res, 444);
            setTimeout(() => {
                console.log(555)
            }, 1000)
        })
    </script>
</body>
</html>